### DISCUSSION TITLE
conditional suggester?

### DISCUSSION THREAD

**Discussion by joshuawagner** [SilentVoid13/Templater#1134] [Help]
When I'm entering data for a new file I sometimes want to leave 'source' field empty but since I'm using `tp.system.suggester` that is of course not possible. Can someone help me with some sort of conditional solution?
```
source: "[[<% (await tp.system.suggester((item) => item.basename, app.vault.getMarkdownFiles(),false,"[[source]]")).basename %>]]"
```

The following is the frontmatter in the template file I use:

```yaml
<%*
await tp.system.prompt("prompt", "Needed: zetCode(a), catName, fileName, title, & shortName");
const zetCode = await tp.system.prompt("zetCode", "e.g.: p####a where # is the zetCode and a is any letter");
const catName = await tp.system.prompt("catName", "catName (for index lookup)");
const fileName = await tp.system.prompt("fileName (no extension)", "reading notes - literatureTitle (author, year)");
const title = await tp.system.prompt("title","reading notes - ");
const shortName = await tp.system.prompt("shortName","reading notes - ");
await tp.file.rename(`${fileName}`);
await tp.file.move(`/thought/litNotes/${fileName}`);
%>---
objType: litNote
created: <% tp.date.now("YYYY-MM-DD") %>
title: "<% title %>"
aliases: "<% zetCode %> - <% title %>"
zetCode: <% zetCode %>
status: 
version: 1.4.0
publish: true
shortName: "<% shortName %>"
source: "[[<% (await tp.system.suggester((item) => item.basename, app.vault.getMarkdownFiles(),false,"[[source]]")).basename %>]]"
category: <% tp.file.cursor() %>
relCategory: <% tp.file.cursor() %>
relZet: <% tp.file.cursor() %>
note: <% tp.file.cursor() %>
context: <% await tp.system.prompt("context", "") %>
---
```
