### DISCUSSION TITLE
Nested template: not moving file correctly.

### DISCUSSION THREAD

**Discussion by tes2ube** [SilentVoid13/Templater#1345] [Help]
Hi all,

I have a template called tem.sort which checks frontmatter "noteType" for a parameter, and based on the string it matches it moves the affected file to the corresponding folder. The code:
```js
<%*
const noteTypeMap = {
    character: "/4. Tabletop/1. Campaign/Characters/",
    session: "/4. Tabletop/1. Campaign/"
};

const noteType = tp.frontmatter.noteType;

if (noteType in noteTypeMap) {
    const newFolderPath = noteTypeMap[noteType];
    await tp.file.move(newFolderPath + tp.file.title);
} else {
    tp.file.cursor_append("> *error*: no corresponding noteType found \n");
}
%>
```

This works totally fine & as intended. However, when I attempt to call the template from another template by running the parent template on the same note, it always returns as `> *error*: no corresponding noteType found`. The code I use to attempt to call it:
```js
<%* await
tp.hooks.on_all_templates_executed(async () => {
    await tp.file.include("[[tem.sort]]");
});
%>
```

I'm sure I'm doing something wrong; no matter how I try to run it, if the nested tem.sort shows up at all in the note which it's applied to, it shows up _before_ the YAML frontmatter I'm attempting to insert.

Dunno if it matters, but here's the parent template I'm trying to insert it into in full context:

---

```YAML
---
aliases:
  - <% tp.file.title.split(" ")[0] %>
tags:
  - dnd/character
abstract: NoteAbstractDescription
zettelTime: <% tp.date.now("YY MMDD HHmm") %>
noteType:
  - character
sessionIntro: 
location: 
ancestry: 
association: 
age: 
anthrochronicity: 
temperament: 
dramatusPersonae: 
voiceProfile: 
---
```
```js
<%* await
tp.hooks.on_all_templates_executed(async () => {
    await tp.file.include("[[tem.sort]]");
});
%>
```
(start of note content goes here)

# Storylines

```dataview
TABLE abstract, association, treasure
FROM [[]]
WHERE contains(notetype, "storyline")
SORT file.name ASC
```

# General

---

Please let me know if you have any ideas. Thanks!
