### ISSUE TITLE
Templater script inserting newline before front matter

### ISSUE THREAD

**Issue by kwatzz** [SilentVoid13/Templater#1366]
**Plugin information (please complete the following information):**

-   OS: Windows 11
-   Templater version: 2.2.3
-   Obsidian version: 1.5.12
-   Templater settings: Template folder location: "3. Resources/Templates"
**Describe the bug**
I am using templater to generate running logs for me. I have the below script which solely has front matter properties:

```
---
    tags: 
    - running-log
    date: "{{date}}"
    zone5_time: <% tp.system.prompt("Enter Zone 5 time (HH:MM:SS or MM:SS if < 1 hour)") %>
    zone4_time: <% tp.system.prompt("Enter Zone 4 time (HH:MM:SS or MM:SS if < 1 hour)") %>
    zone3_time: <% tp.system.prompt("Enter Zone 3 time (HH:MM:SS or MM:SS if < 1 hour)") %>
    zone2_time: <% tp.system.prompt("Enter Zone 2 time (HH:MM:SS or MM:SS if < 1 hour)") %>
    zone1_time: <% tp.system.prompt("Enter Zone 1 time (HH:MM:SS or MM:SS if < 1 hour)") %>
    avg_stride_length_m: <% tp.system.prompt("Enter average stride length in meters") %>
    avg_ground_contact_time_ms: <% tp.system.prompt("Enter average ground contact time in milliseconds") %>
    avg_vertical_oscillation_cm: <% tp.system.prompt("Enter average vertical oscillation in centimeters") %>
    avg_heart_rate_bpm: <% tp.system.prompt("Enter average heart rate in bpm") %>
    avg_cadence_spm: <% tp.system.prompt("Enter average cadence in steps per minute") %>
    avg_power_watts: <% tp.system.prompt("Enter average power in watts") %>
    elevation_gain_m: <% tp.system.prompt("Enter elevation gain in meters") %>
    active_calories_kcal: <% tp.system.prompt("Enter active calories burned in kcal") %>
    distance_km: <% tp.system.prompt("Enter distance in kilometers") %>
    time: <% tp.system.prompt("Enter time in HH:MM:SS format o MM:SS if  < 1 hour") %>
    run_type: <% tp.system.suggester(  ["Tempo Run", "Recovery Run", "Long Run", "Backyard Ultra Simulation", "Back-to-Back Long Run", "Hill Repeats", "Fartlek"],  ["Tempo Run", "Recovery Run", "Long Run", "Backyard Ultra Simulation", "Back-to-Back Long Run", "Hill Repeats", "Fartlek"],  false,  "What type of run would you like to log?") %>
    ---
```

I then use the below script to generate the note and prompt me for date

```
    <%*
    const dateChoice = await tp.system.suggester(
      ["Today", "Yesterday", "Custom"],
      ["today", "yesterday", "custom"],
      false,
      "What date was your run?"
    );
    
    let dateStr;
    if (dateChoice === "today") {
      dateStr = tp.date.now("YYYY-MM-DD");
    } else if (dateChoice === "yesterday") {
      dateStr = tp.date.now("YYYY-MM-DD", -1);
    } else {
      dateStr = await tp.system.prompt("Enter the date (YYYY-MM-DD)");
    }
    
    const folderPath = "Journal/Fitness Log";
    const title = `${dateStr} Running Log`;
    const templatePath = "Resources/Templates/Run Log Template";
    
    await tp.file.create_new(title, folderPath, true);
    await tp.file.move(folderPath + "/" + title);
    
    const newFilePath = folderPath + "/" + title + ".md";
    const templateContent = await tp.file.include("[[" + templatePath + "]]");
    const finalContent = templateContent.replace("{{date}}", dateStr);
    
    const contentToWrite = finalContent.replace(/^\s+/, '');
    
    console.log(`Content to be written:\n${contentToWrite}`); 
    
    await app.vault.modify(app.vault.getAbstractFileByPath(newFilePath), contentToWrite);
    %>
```

No matter what I do (including the above attempt to replace white spaces/newlines), there is a newline before the YAML, causing obsidian to fail to render the properties correctly. Everything else is correct. Any ideas? Nothing I do seems to fix it, and I checked that the template md file itself has no leading whitespace or newline.

**Expected behavior**
The first line should be ---, not a blank line. 

**Screenshots**
![image](https://github.com/SilentVoid13/Templater/assets/40744880/7062b937-e0a6-4b74-bcbb-839a4b9facd7)
![image](https://github.com/SilentVoid13/Templater/assets/40744880/3b86d01b-e8a4-4d64-9c13-99ec8a34d907)
