### ISSUE TITLE
Modify tp.file.include to optionally omit frontmatter data (default = false for backwards compatability)

### ISSUE THREAD

**Issue by sigmoid-azoth** [SilentVoid13/Templater#292]
## **Is your feature request related to a problem? Please describe.**
I'd like to omit frontmatter data from the result of `tp.include()` calls so that the templates themselves can have frontmatter data which isn't included in the generated file. 

Example:

```yaml
---
template:
    scope       : 
    type        : template~uri
    title       : URI
    description : uri template
    aliases     : [URI template]
    tags        : [NOTE/OBJECT/TEMPLATE, Obsidian/template/uri, Obsidian/template, uri]
    
---
```

Currently, I am using https://github.com/sigmoid-azoth/obsidian-advanced-uri to regex replace sections

```javascript
<%*
await open("obsidian://advanced-uri?vault=" + encodeURI(app.vault.adapter.basePath.split("\\").reverse()[0]) + "&searchregex=" + encodeURI(/---\ntemplate:(.*\n(?!---))+(\s+\n)?---\n/g) + "&remove=true");
_%>
```

This works okay but it could be destructive as it is a blind replace operation rather than cleaner templater generation code. ~~Additionally, the `await open()` call doesn't appear to work the same on mobile.~~<sup>[1](#caveat)</sup>

## **Describe the solution you'd like**

syntax like `tp.file.include("[[TFile]]", true)` where the second parameter is optional and defaults to `false`. `true` would omit the frontmatter from included pages.

## **Describe alternatives you've considered**
I'm a little in over my head with this kind of thing. I think this is a very good solution.

---
<a name="caveat">1</a>: possibly caused by obsidian-advanced-uri
