### ISSUE TITLE
Have a heart for people with bad eyesight—use more theme colors, not hardcoded ones

### ISSUE THREAD

**Issue by Moonbase59** [SilentVoid13/Templater#303]
**Is your feature request related to a problem? Please describe.**
My eyesight isn’t the best anymore. I mostly use Obsidian’s default light theme, and _Templater_’s code is totally unreadable for me. That’s extremely stressy on my eyes, since I use Templater a lot.

**Describe the solution you'd like**
If anyhow possible, could you use the theme’s color variables (mostly), and colors that are more readable in _both_ dark & light themes otherwise? In your plugin’s `styles.css`, all these are currently hard-coded.

**Describe alternatives you've considered**
Make a CSS snippet to change Templater’s colors, but it would be nicer if the plugin had readable text as it comes.

**Additional context**

Example screenshot:

![Knowledgebase - Obsidian v0 12 10_070](https://user-images.githubusercontent.com/3706922/126896401-a42c5a80-b94d-4c77-b6ee-cc88d4a224a3.png)

**Comment by Moonbase59** [comment]
Just saw #268 is related.

**Comment by chrisgrieser** [comment]
I also support this – I don't even have bad eyesight and still have trouble reading templater code :(

**Comment by Larandar** [comment]
Added note: it's not just about the colours, font size too (templates in headers in particular)

**Comment by Moonbase59** [comment]
For the time being, until this gets fixed, I went for some radical surgery in order to at least be able to _use_ _Templater_ again:

In the plugin’s folder, `.obsidian/plugins/templater-obsidian/`, I made a backup of the existing `styles.css`, then **radically removed all CodeMirror styling**, so only the CSS required for its settings stay:

```css
.templater_div {
    border-top: 1px solid var(--background-modifier-border);
}

.templater_div > .setting-item {
    border-top: none !important;
    align-self: center;
}

.templater_div > .setting-item > .setting-item-control {
    justify-content: space-around;
    padding: 0;
    width: 100%;
}

.templater_div > .setting-item > .setting-item-control > .setting-editor-extra-setting-button {
    align-self: center;
}

.templater_title {
    margin: 0;
    padding: 0;
    margin-top: 5px;
    text-align: center;
}

.templater_template {
    align-self: center;
    margin-left: 5px;
    margin-right: 5px;
    width: 70%;
}

.templater_cmd {
    margin-left: 5px;
    margin-right: 5px;
    font-size: 14px;
    width: 100%;
}

.templater_div2 > .setting-item {
    align-content: center;
    justify-content: center;
}

.templater_button:hover {
    background-color: #00496A !important;
}

.templater-prompt-div {
    display: flex;
}

.templater-prompt-form {
    display: flex;
    flex-grow: 1;
}

.templater-prompt-input {
    flex-grow: 1;
}
```

Doesn’t look beautiful, but at least I can _read it again_:

![Templater Test - Knowledgebase - Obsidian 0 12 12_141](https://user-images.githubusercontent.com/3706922/129700894-97f8546d-aae3-42ad-b3df-33f9ec9dccfb.png)

**Comment by chrisgrieser** [comment]
as an easy temporary fix, you can also use this css snippet that I wrote yesterday. It changes font color in light mode, making the templater code readable for me.

```css
/* templater readable with light theme */
.theme-light .cm-s-obsidian .cm-templater-command.cm-comment{
	color: #939393 !important;
}
.theme-light .cm-s-obsidian .cm-templater-command.cm-keyword {
 	color: #5C71FC !important;
}
.theme-light .cm-s-obsidian .cm-templater-command.cm-def {
	color: #008100 !important;
}
.theme-light .cm-s-obsidian .cm-templater-command.cm-string {
	color: #A0A200 !important;
}
.theme-light .cm-s-obsidian .cm-templater-command.cm-undefined,
.theme-light .cm-s-obsidian .cm-templater-command.cm-variable,
.theme-light .cm-s-obsidian .cm-templater-command.cm-property {
	color: #111 !important;
}
```
