### ISSUE TITLE
Reading frontmatter of other notes, like Dataview can

### ISSUE THREAD

**Issue by Moonbase59** [SilentVoid13/Templater#344]
**Is your feature request related to a problem? Please describe.**
I need to access the frontmatter of a central "parameters" file which holds standard data in YAML, so I don’t have to change hundreds of notes if something changes. This looks like so (example):

**File `parameters.md`:**

```yaml
---
general:
  dateformat:
    luxon: "yyyy-MM-dd"
    moment: "YYYY-MM-DD"
  datetimeformat:
    luxon: "yyyy-MM-dd HH:mm"
    moment: "YYYY-MM-DD HH:mm"
---
```

I can access these values with _Dataview_ just fine:

````
**Dataview using file reference `[[parameter]]`:**

`=[[parameter]].general.datetimeformat.luxon`
````

but didn’t find a function in _Templater_ that allows this. Using `tp.frontmatter` only works for the currently open note.

**Describe the solution you'd like**
A function that allows reading frontmatter YAML like _Dataview_ can, maybe extending the `tp.frontmatter` syntax like so:

```
<%+ tp.frontmatter("[[parameter]]").general.datetimeformat.luxon %>
```

**Describe alternatives you've considered**
Played around with lots of templater functions, but to no avail.

**Additional context**
![Dataview   Templater - Tips   Tricks (2021-08-09) - Knowledgebase - Obsidian 0 12 12_001](https://user-images.githubusercontent.com/3706922/131047272-d4d787a9-6e63-4e08-bead-58b17e1e29d4.png)
