### ISSUE TITLE
New format that replaces curly brackets doesn't work for me

### ISSUE THREAD

**Issue by filmgal** [SilentVoid13/Templater#75]
I noticed that the documentation indicates a change in how to insert the templates by replacing some curly brackets with `<% %>`  I have had no luck doing that. Only the items in curly brackets work.

Example:
`{{tp_title}}` inserts the title, ` <% tp.file.title %>`, does not.

I've tried it with the Obsidian core template plugin disabled and enabled, but got the same results in both cases. Am I doing something wrong?

Obsidian 11.9
Templater 0.5.7

**Comment by kiraarghy** [comment]
I'm having the same issue!

**Comment by filmgal** [comment]
> I assume it's because the one of the community plugins is v0.5.7 and the Internal docs were just updated ~4 hours ago for the v1.0.0 release?

Ah, good catch

**Comment by SilentVoid13** [comment]
You need to update the plugin. Is it working if you update ?

**Comment by filmgal** [comment]
Odd, because I updated the plug-in today just by clicking on "update" after selecting your plugin in the "community plugins" page.  Turns out that the "real" updates are only available within Obsidian when selecting "Update All" next to Community Plugins>Community Plugins.

**Comment by filmgal** [comment]
Not working for me at all. 

2 things: Obsidian keeps saying "template parsing error. Aborting" in the upper right whenever I use templater with just this in the template:  `date now:  <% tp.date.now() %>`  Also tried with just this: `<% tp.title %>`. 

Neither of them render when I use the template.

Also, every time I restart Obsidian the new details about the updated version of Templater display in the upper right.

![image](https://user-images.githubusercontent.com/30246308/113643119-856c9280-964f-11eb-8b1a-fdd5cfe2f6d6.png)

**Comment by cassidoo** [comment]
I'm getting a "Metadata (Invalid YAML)" when I put this in my frontmatter!

```yaml
---
uuid: test<% tp.file.creation_date(format: string = "YYYYMMDD-HHmmss") %>
alias: "Teston <% tp.date.now(format: string = "MMM Do, YYYY") %>"
dates:
  created: <% tp.file.creation_date(format: string = "YYYY-MM-DDTHH:mm:ss") %>
  last-updated: <% tp.file.last_modified_date(format: string = "YYYY-MM-DDTHH:mm:ss") %>
tags: #test
---
```

**Comment by SilentVoid13** [comment]
Hey @cassidoo, you copy-pasted the template documentation, you now have to call template functions like functions.
Check the README for this: https://github.com/SilentVoid13/Templater#internal-modules

In your case this would give:

```yaml
---
uuid: test<% tp.file.creation_date("YYYYMMDD-HHmmss") %>
alias: "Teston <% tp.date.now("MMM Do, YYYY") %>"
dates:
  created: <% tp.file.creation_date("YYYY-MM-DDTHH:mm:ss") %>
  last-updated: <% tp.file.last_modified_date("YYYY-MM-DDTHH:mm:ss") %>
tags: #test
---
```

**Comment by SilentVoid13** [comment]
@filmgal That's weird, try uninstalling and reinstalling Templater maybe something went wrong when updating. Tell me how this goes.

**Comment by Cole-Di-Pasqualucci** [comment]
Same thing happens to me and yep that does nothing :/

**Comment by cassidoo** [comment]
![image](https://user-images.githubusercontent.com/1454517/113795827-646d7580-9713-11eb-8196-b63f67c8ad49.png)
This is still showing invalid metadata, @SilentVoid13!

**Comment by SilentVoid13** [comment]
@cassidoo Forgot about the double quotes inside the double quotes. Use single quotes and it should work fine:

```yaml
---
uuid: test<% tp.file.creation_date("YYYYMMDD-HHmmss") %>
alias: "Teston <% tp.date.now('MMM Do, YYYY') %>"
dates:
  created: <% tp.file.creation_date("YYYY-MM-DDTHH:mm:ss") %>
  last-updated: <% tp.file.last_modified_date("YYYY-MM-DDTHH:mm:ss") %>
tags: #test
---
```
